# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Golden D6
email: theGoldenD6@gmail.com
description: 
The Golden D6 is a wargaming magazine for every gamer out there.
The magazine is created in a high quality PDF format for you to download and enjoy. As soon as you buy your copy, you can immediately download it and begin enjoying it. There’s no waiting at the mailbox for the mail to be delivered. The Golden D6 is available for download immediately! It’s a one-of-a-kind wargaming magazine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://goldend6.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: spruegrey
github_username:  goldend6

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
